### ISSUE TITLE
New Queue Not Started

### ISSUE THREAD

**Issue by lukashambsch** [sorentwo/oban#580] opened 2021-11-01 22:51 UTC
### Environment

- Oban Version - 2.9.2
- PostgreSQL Version - 13.4
- Elixir & Erlang/OTP Versions (`elixir --version`) - 1.11.4 and 23.3.1

### Current Behavior

I added a new queue to my config and it wasn't started. It started correctly when I manually ran `Oban.start_queue(...` from the shell.

### Expected Behavior

I expected the new queue to be picked up because of the config passed in `application.ex`

### Code

**application.ex**

```
do
  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  @moduledoc false

  use Application

  def start(_type, _args) do
    children = [
      # Start the Ecto repository
      TrackBoost.Repo,
      # Start the Telemetry supervisor
      TrackBoostWeb.Telemetry,
      # Start the PubSub system
      {Phoenix.PubSub, name: TrackBoost.PubSub},
      # Start the Endpoint (http/https)
      TrackBoostWeb.Endpoint,
      {Oban, oban_config()},
      # Start a worker by calling: TrackBoost.Worker.start_link(arg)
      # {TrackBoost.Worker, arg}
      # Supervisors for background jobs
      {Task.Supervisor, name: TrackBoost.Shops.SeedSupervisor},
      # Segment genserver
      {Segment, Application.get_env(:segment, :write_key)}
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: TrackBoost.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  def config_change(changed, _new, removed) do
    TrackBoostWeb.Endpoint.config_change(changed, removed)
    :ok
  end

  # Conditionally disable queues or plugins here.
  defp oban_config do
    Application.fetch_env!(:track_boost, Oban)
  end
end
```

**config**
```
config :track_boost, Oban,
  repo: TrackBoost.Repo,
  plugins: [
    Oban.Plugins.Pruner,
    {Oban.Plugins.Cron,
     crontab: [
       {"0 0,12 * * *", TrackBoost.Workers.OrderReconciliation}
     ]}
  ],
  queues: [default: 1, shopify_webhooks: 1, easy_post_webhoooks: 1, reconciliation: 1]
```

**Comment by sorentwo** [comment] 2021-11-02 12:02
Is this consistent across restarts? Which queue is it?

**Comment by sorentwo** [comment] 2021-11-03 20:30
@lukashambsch This is the only report I've seen of a queue not starting based on configuration (especially something as straightforward as what you've shown). I'm closing this as an application restart or configuration error, and not a bug within Oban. If you have more questions or need support please ask on the Elixir Forum or in #oban on Slack.

**Closed by sorentwo** 2021-11-03 20:30 UTC

**Comment by lukashambsch** [comment] 2021-11-05 22:23
@sorentwo Thanks for the quick reply! Sorry for my slow reply, I missed the notification. I'll reach out in one of those other channels.
