### ISSUE TITLE
Timeout exit in `GenServer.call(Oban.Notifier, {:listen, [:signal]}, 5000)`

### ISSUE THREAD

**Issue by halostatue** [sorentwo/oban#317] opened 2020-08-27 02:13 UTC
### Environment

- 2.1.0
- 9.6.6
- Elixir 1.10.4 (Erlang OTP 22.3.4.9)

I’ve been running Oban 2.0 as part of our upgrade to Elixir 1.10. This is running in our test environment. I’ve received the following error through Sentry:

```
Sentry.CrashError: ** (exit) exited in: GenServer.call(Oban.Notifier, {:listen, [:signal]}, 5000)
    ** (EXIT) time out
  File "lib/gen_server.ex", line 1023, in GenServer.call/3
  File "lib/oban/midwife.ex", line 33, in Oban.Midwife.handle_continue/2
  File "gen_server.erl", line 637, in :gen_server.try_dispatch/4
  File "gen_server.erl", line 388, in :gen_server.loop/7
  File "proc_lib.erl", line 249, in :proc_lib.init_p_do_apply/3
```

The closest I can find is #21, but that doesn’t feel like the same issue.

**Comment by sorentwo** [comment] 2020-08-27 22:12
This was most likely caused by a cascade of slow connections. The sequence would be like this:

1. `Oban.Notifier` starts and attempts to open a new connection in a `handle_continue`
2. `Oban.Midwife` starts and attempts to start listening to messages via the notifier in a `handle_continue`
3. `Oban.Notifier` still hasn't connected and the `handle_continue` hasn't returned, so the listen call from `Oban.Midwife` times out

Is this happening repeatedly or was this a one off? I suspect this could happen intermittently due to load on the test database or a connection limit.

The only change that we could make would be to increase the `listen` timeout, but that would be a band-aid and could just as easily fail if the connection took longer.

**Comment by halostatue** [comment] 2020-08-28 00:59
It looks like a single instance of the issue for the moment, and the database is relatively small (it’s one of Heroku’s non-free small test databases).

**Comment by sorentwo** [comment] 2020-08-28 19:51
I'm going to close this as a random connection issue / timeout bug. I don't believe there is a library level fix for it (aside from some possible documentation).

**Closed by sorentwo** 2020-08-28 19:51 UTC
Labels: bug

**Comment by threeaccents** [comment] 2022-07-13 15:43
@sorentwo Where could that listen timeout config be updated?

**Comment by sorentwo** [comment] 2022-07-13 19:06
@threeaccents There isn't anywhere to set that config. The notifier has changed a lot since this issue was opened, and there's now a distributed erlang notifier available as well if you're having ongoing issues.
