### ISSUE TITLE
Workers Workflow are not taking dependencies into account

### ISSUE THREAD

**Issue by sergiorjsd** [sorentwo/oban#519] opened 2021-07-16 13:49 UTC
### Environment

- Oban version: 2.7.1
- Oban Pro version: 0.8.1
- PostgreSQL Version: 12.7
- Elixir 1.12.2 (compiled with Erlang/OTP 24)

### Current Behavior
I think I have found a bug in Workers Workflows behaviour (or maybe I'm using it the wrong way). I have a workflow created with several steps. These steps depends on the first executed but they are not taken into account and the last ones are executed before the first ones. I've created an example to reproduce it:

```
defmodule Example do
  def run do
    report_ids = [1, 2, 3]
    finish_deps = Enum.map(report_ids, &"ack_#{&1}")
​
    CheckStatus.new_workflow()
    |> CheckStatus.add(:detector, CheckStatus.new(%{}))
    |> add_downloader_jobs(report_ids)
    |> add_ack_jobs(report_ids)
    |> FinishWorkflow.add(:finish, FinishWorkflow.new(%{}), deps: finish_deps)
    |> Oban.insert_all()
  end
​
  def add_downloader_jobs(workflow, ids) do
    for id <- ids, reduce: workflow do
      workflow ->
        job = DownloadReport.new(%{})
        CheckStatus.add(workflow, "report_#{id}", job, deps: [:detector])
    end
  end
​
  def add_ack_jobs(workflow, ids) do
    deps = Enum.map(ids, &"report_#{&1}")
​
    for id <- ids, reduce: workflow do
      workflow ->
        job = DownloadAck.new(%{})
        CheckStatus.add(workflow, "ack_#{id}", job, deps: deps)
    end
  end
end
​
defmodule CheckStatus do
  use Oban.Pro.Workers.Workflow, queue: :default, max_attempts: 20
​
  def process(_job) do
    :timer.sleep(1_000)
    {:snooze, 5}
  end
end
​
defmodule DownloadReport do
  use Oban.Pro.Workers.Workflow, queue: :default, max_attempts: 20
​
  def process(_job), do: {:snooze, 5}
end
​
defmodule DownloadAck do
  use Oban.Pro.Workers.Workflow, queue: :default, max_attempts: 20
​
  def process(_job), do: {:snooze, 5}
end
​
defmodule FinishWorkflow do
  use Oban.Pro.Workers.Workflow, queue: :default, max_attempts: 20
​
  def process(_job), do: {:ok, nil}
end
```

As you can see, `DownloadReport` depends on `CheckStatus`, `DownloadAck` on all `DownloadReport` and `FinishWorkflow` in all `DownloadAck`. However, this is my Oban current status:

**Completed:**
![image](https://user-images.githubusercontent.com/12546904/125954202-76a758fb-57d9-48b5-82a8-8e8e71e4972a.png)

**Scheduled:**
![image](https://user-images.githubusercontent.com/12546904/125954314-fc2f3e40-4f85-4903-97d3-3512d85b6d3e.png)

In **meta** can be seen that dependencies are set correctly:

**For the Finish job**:
```
Meta
%{
  "deps" => ["ack_1", "ack_2", "ack_3"],
  "name" => "finish",
  "workflow_id" => "3fe81936-fb82-4401-90f9-28f736eda84f"
}
```

**For an Ack job**:
```
Meta
%{
  "deps" => ["report_1", "report_2", "report_3"],
  "name" => "ack_2",
  "workflow_id" => "3fe81936-fb82-4401-90f9-28f736eda84f"
}
```

**For a DownloadReport job**:
```
Meta
%{
  "deps" => ["detector"],
  "name" => "report_1",
  "workflow_id" => "3fe81936-fb82-4401-90f9-28f736eda84f"
}
```

**For CheckStatus job**:
```
Meta
%{
  "deps" => [],
  "name" => "detector",
  "workflow_id" => "3fe81936-fb82-4401-90f9-28f736eda84f"
}
```

### Expected Behavior
I was expecting that the jobs that depends in others that are not completed were not executed.

**Comment by sorentwo** [comment] 2021-07-16 15:06
@sergiorjsd Thanks for the report and the detailed steps to help reproduce. At first glance, everything looks correct to me. I'll look into it to debug and report back.

**Comment by sorentwo** [comment] 2021-07-26 19:57
@sergiorjsd Sorry for the delay. I took some time to investigate this today and noticed that the workflow would never finish with the sample code you shared. That's because the jobs infinitely return `{:snooze, 5}`, which means all of the jobs will keep retrying indefinitely. When I change the definitions to something that will eventually complete, like this:

```elixir
defmodule CheckStatus do
  use Oban.Pro.Workers.Workflow, queue: :default, max_attempts: 20

  def process(_job) do
    :timer.sleep(1_000)

    if :rand.uniform > 0.5 do
      {:snooze, 5}
    else
      :ok
    end
  end
end

defmodule DownloadReport do
  use Oban.Pro.Workers.Workflow, queue: :default, max_attempts: 20

  def process(_job) do
    if :rand.uniform > 0.5 do
      {:snooze, 5}
    else
      :ok
    end
  end
end

defmodule DownloadAck do
  use Oban.Pro.Workers.Workflow, queue: :default, max_attempts: 20

  def process(_job) do
    if :rand.uniform > 0.5 do
      {:snooze, 5}
    else
      :ok
    end
  end
end
```

Then the dependencies resolve, and eventually, all the jobs finish.

To test and verify this, I plugged in your workflow example locally. Here is what the job id, state, attempts, and max_attempts looked like before I made any changes:

```
   id    │   state   │ attempt │ max_attempts
═════════╪═══════════╪═════════╪══════════════
 1222426 │ scheduled │      27 │           47
 1222425 │ scheduled │      27 │           47
 1222423 │ scheduled │      27 │           47
 1222427 │ scheduled │      27 │           47
 1222429 │ scheduled │      27 │           47
 1222428 │ scheduled │      27 │           47
 1222430 │ executing │      27 │           46
 1222424 │ scheduled │      27 │           47
```

After redefining the workers so they could eventually complete, they started to transition as expected. First, with many of them executing and only one completed:

```
   id    │   state   │ attempt │ max_attempts
═════════╪═══════════╪═════════╪══════════════
 1222426 │ executing │      53 │           72
 1222425 │ executing │      53 │           72
 1222423 │ completed │      53 │           72
 1222427 │ executing │      53 │           72
 1222429 │ executing │      53 │           72
 1222428 │ executing │      53 │           72
 1222430 │ executing │      53 │           72
 1222424 │ executing │      53 │           72
```

Then, after a few more tries (and the addition of a worker in the query):

```
   id    │   state   │     worker     │ attempt │ max_attempts
═════════╪═══════════╪════════════════╪═════════╪══════════════
 1222426 │ completed │ DownloadReport │      53 │           72
 1222423 │ completed │ CheckStatus    │      53 │           72
 1222425 │ completed │ DownloadReport │      53 │           72
 1222429 │ completed │ DownloadAck    │      54 │           73
 1222427 │ completed │ DownloadAck    │      54 │           73
 1222428 │ completed │ DownloadAck    │      54 │           73
 1222424 │ completed │ DownloadReport │      54 │           73
 1222430 │ completed │ FinishWorkflow │      54 │           73
```

The screenshots you shared above show the `DownloadAck` job as complete, which is impossible with the snoozing code that you shared. If there is some other code or details that you can share, I'll re-investigate. As is, things work exactly as I'd expect  🙂

**Comment by sergiorjsd** [comment] 2021-07-28 10:49
Thanks for your response but I'm having the same issue :smile:

That's the weirdest thing! These jobs should never be completed because they are returning `{:snooze, time}`.

Because of this I think that there is something that is completing this jobs becuase they're not doing it by theirselfs. If I put an `IO.inspect` or a `IEx.pry()` inside `FinishWorkflow.process/1` function... this code is never executed (but the job is marked as completed).

Here it's a video where this is happening. I show the enqueued jobs (with the queue stopped) with their dependencies. And everything goes fine until 1:25. At this point, you can see what happened :disappointed: 

https://user-images.githubusercontent.com/12546904/127307128-959a4d8c-65f1-45b8-9dea-079d55d74153.mp4

And the code I'm running is the provided at description. I'm running this code inside my app which has the following Oban config:

```
config :myapp, Oban,
  engine: Oban.Pro.Queue.SmartEngine,
  repo: Myapp.Repo,
  plugins: [
    {Oban.Plugins.Repeater, []},
    {Oban.Plugins.Gossip, []},
    {Oban.Pro.Plugins.Lifeline, []},
    {Oban.Pro.Plugins.BatchManager, []},
    {Oban.Web.Plugins.Stats, []},
    {
      Oban.Plugins.Cron,
      timezone: "Europe/Madrid",
      crontab: [ ... ]  
    }
  ],
  queues: [default: 5, workflows: 5, bulk: 5]
```

Can I provide you any kind of information that could help you reproduce it?

PS: I've recorded the video the first time I tried to reproduce it and it happened. But (another weird thing) the second time I enqueued the workflow to test the code inside `process/1` was not executed it WAS NOT happening... until I paused the queue and resume it.

**Comment by sorentwo** [comment] 2021-07-28 21:09
After double-checking that there isn't any mechanism for the workflow itself to mark a job `completed`, I re-ran the experiment locally using the exact code you shared. The result was exactly the same. I've attached a recording of the dashboard (filtered by the worker id and `scheduled` state):


https://user-images.githubusercontent.com/270831/127396174-8bdbe061-b1de-450e-9e34-dd1190edce13.mov

Is it possible that you have another server or process that's running? Maybe something with a different implementation of those modules?

**Comment by sergiorjsd** [comment] 2021-07-29 06:08
I don't have any other server, process or different implementations :smile: It's an example created just for this issue.

Anyway it seems to be a problem of my app so I'll try to check why this is happening or try to reproduce it in an empty phoenix project.

Thanks for your time!

**Comment by sorentwo** [comment] 2021-07-29 13:41
If you find any other clues or have some insight, please let me know!

**Comment by sergiorjsd** [comment] 2021-07-30 11:45
@sorentwo Hello again! 

That's the last try :smile: I've created this repo: https://github.com/sergiorjsd/dep_bug where it's happening the issue. Also I've asked to 3 friends of mine to test the problem and they've been able to reproduce it I hope you also can.

I've reduced the snooze time from 5 seconds to 1 second in this example and also I've reduced the workflow steps in order to simplify it and make it faster.

Could you check it? Check the `Readme.md` for configuration.

**Comment by crbelaus** [comment] 2021-07-30 12:31
Our expectation is that, since the `CheckStatus` never completes, the dependand `DownloadReport` would never execute.

Turns out that they get marked as completed even though they never run. If they ran we would see the information in the Log and they would never complete since they always snooze.

There are two big questions here:
- Why do dependant jobs get marked as completed even if their dependencies are not completed yet?
- Who do dependant jobs get marked as completed even if the `process` function never ran?

**Closed** 2021-07-30 14:28 UTC
Labels: area:pro, kind:bug

**Comment by sorentwo** [comment] 2021-07-30 14:44
@sergiorjsd @crbelaus Thank you for recreating the situation with that repo. That helped me finally track down the issue! The linked commit describes the problem, but the short version is that the snooze calculation was wrong, and Oban ignored it.

Watch for releases of Oban and Pro today 💛
