### ISSUE TITLE
oban_web - `KeyError` in `Oban.Web.Jobs.SortComponent.render/1`

### ISSUE THREAD

**Issue by whatyouhide** [sorentwo/oban#1057] opened 2024-03-20 11:01 UTC
### Environment

- Oban Versions:
![CleanShot 2024-03-20 at 12 01 28@2x](https://github.com/sorentwo/oban/assets/3890250/fc508c1f-c0c8-4d64-bdd7-6784bfe663ec)

- PostgreSQL Version — 13.2
- Elixir & Erlang/OTP Versions (`elixir --version`) — 1.16.1 and 26.0.2

### Current Behavior

This could be us doing something wrong, but the stacktrace is all ObanWeb:

![CleanShot 2024-03-20 at 12 00 28@2x](https://github.com/sorentwo/oban/assets/3890250/901e3f16-cc34-4432-8ee9-4a259482400a)

**Comment by sorentwo** [comment] 2024-03-20 11:18
This has happened intermittently for a while, but never reliably and I'm unable to reproduce it. It seems like a race condition in LV (or a misunderstanding on my part), because `handle_params/3` should always be called before `render/1`, and `handle_params/3` sets defaults.

Are you able to reproduce the error?

**Comment by whatyouhide** [comment] 2024-03-20 11:24
@sorentwo nope and I don't have time to do right now so since we use oban_web for monitoring but that's pretty much it, sorry 😩 Feel free to close this one out or we can try to help some of the LV folks, but I won't be able to help much in practice.

**Comment by sorentwo** [comment] 2024-03-20 11:26
I'll ask the LV people before closing this out. People have mentioned this issue for a long time now, and I'd like to sort it out.

**Comment by sorentwo** [comment] 2024-03-20 15:55
@whatyouhide on a tip off from Chris, I think this is sorted 👍

**Closed** 2024-03-20 15:54 UTC
Labels: kind:bug, area:web

**Comment by whatyouhide** [comment] 2024-03-20 16:06
Nice! Thank you both then 🙃 💟
